Test cat unique count
UBC-MDS/slimeda pull request #27
Opened 2022-01-18 13:25 UTC by thayeylolu

- [ ] Write basic unit test
- [ ] include a sample dataset
- [ ] include parametrisation of bad input
-

2022-01-19 17:52 UTC, Anthea98 commented on tests/test_cat_unique_counts.py
> +def test_cat_unique_counts():
we need 3-5 edge cases~maybe one more case~

2022-01-19 17:57 UTC, Anthea98 requested changes
GOOD JOB! some suggestions are here~

2022-01-19 17:57 UTC, Anthea98 commented on tests/test_cat_unique_counts.py
> +
we need 3-5 edge cases in the unit test, maybe add one more case~

2022-01-19 17:57 UTC, Anthea98 commented on tests/test_cat_unique_counts.py
> +    """Unit test for missing value counts."""
"""Unit test for unique value counts."""

2022-01-19 17:57 UTC, Anthea98 commented on tests/test_cat_unique_counts.py
> +    assert result2 == ['Name']
Looks good! How about adding 1-2 tests related to the count number we got? like how many "Alex" here hhh

2022-01-20 02:17 UTC, thayeylolu commented on tests/test_cat_unique_counts.py
> +    """Unit test for missing value counts."""
this is what happens when you copy and paste someone else's code😆

2022-01-20 02:42 UTC, thayeylolu commented on tests/test_cat_unique_counts.py
> +    assert result2 == ['Name']
Great idea.  I will include it. Thank you for the feed back

2022-01-20 03:08 UTC, thayeylolu commented on tests/test_cat_unique_counts.py
> +
Thank you Anthea. I will include it

2022-01-20 03:15 UTC, Anthea98 approved these changes
nice work~

2022-01-20 03:15 UTC, merged